import Foundation
import MLX
import MLXNN
import XCTest

@testable import WanCore

/// Decode-parity gate for the 48-ch channels-last `Wan22VAEDecoder` (TI2V-5B VAE).
///
/// Compares the Swift decode against oracle goldens generated by
/// `/Volumes/DEV_ARCHIVE/ti2v-5b-measure/vae22_parity/gen_golden.py` (mlx-video
/// pin 87db56a, CPU stream). On the CPU stream the port is **bit-exact** vs the
/// oracle (0.0 max-abs at every stage) — `verify: [.all]` passes (every checkpoint
/// key maps) and every op reproduces the oracle's fp32 result exactly.
///
/// CRITICAL: pin the stream with `Device.withDefaultDevice(Device(.cpu)) { … }`,
/// NOT the deprecated `Device.setDefault(device:)` — the latter does NOT actually
/// scope the default device for the ops here, so convs silently run on Metal and
/// lose ~3-4 fp32 bits (donor lesson L10), inflating the decode diff to ~6e-3.
/// The task-local `withDefaultDevice` is what makes the CPU parity bit-exact.
///
/// Fixture-gated: skipped (not failed) when the `DEV_ARCHIVE` fixtures are absent,
/// so the published repo's `swift test` stays green for anyone without the weights.
final class WanVAE22ParityTests: XCTestCase {
    static let fixtureRoot = URL(fileURLWithPath: "/Volumes/DEV_ARCHIVE/ti2v-5b-measure")
    var parityDir: URL { Self.fixtureRoot.appendingPathComponent("vae22_parity") }
    var vaeWeights: URL {
        Self.fixtureRoot.appendingPathComponent("models/ti2v-5b-bf16/vae.safetensors")
    }

    private func requireFixtures() throws {
        let fm = FileManager.default
        for url in [parityDir.appendingPathComponent("video.npy"), vaeWeights] {
            if !fm.fileExists(atPath: url.path) {
                throw XCTSkip("vae22 parity fixtures not present at \(url.path)")
            }
        }
    }

    private func maxAbsDiff(_ a: MLXArray, _ b: MLXArray) -> Float {
        abs(a - b).max().item(Float.self)
    }
    private func meanAbsDiff(_ a: MLXArray, _ b: MLXArray) -> Float {
        abs(a - b).mean().item(Float.self)
    }

    /// Load the decoder + conv2 weights into a fresh decoder, verifying the module
    /// tree matches the (already-sanitized) checkpoint exactly. CPU stream caller.
    private func loadDecoder() throws -> Wan22VAEDecoder {
        let decoder = Wan22VAEDecoder(zDim: 48)
        let weights = try WeightLoader.loadSafetensors(url: vaeWeights)
            .filter { $0.key.hasPrefix("decoder.") || $0.key.hasPrefix("conv2.") }
            .mapValues { $0.asType(.float32) }
        try decoder.update(parameters: ModuleParameters.unflattened(weights), verify: [.all])
        eval(decoder.parameters())
        return decoder
    }

    /// Constant gate: the Swift 48-vec mean/std match the oracle's.
    func testStatsConstantsMatchGolden() throws {
        try requireFixtures()
        let meanG = try loadNumpy(url: parityDir.appendingPathComponent("vae22_mean.npy"))
        let stdG = try loadNumpy(url: parityDir.appendingPathComponent("vae22_std.npy"))
        XCTAssertLessThan(maxAbsDiff(MLXArray(VAE22_MEAN), meanG), 1e-6)
        XCTAssertLessThan(maxAbsDiff(MLXArray(VAE22_STD), stdG), 1e-6)
    }

    /// Pure-stats gate: `denormalizeLatents22(z_norm)` must reproduce `z_denorm`.
    func testDenormalizeLatentsMatchesGolden() throws {
        try requireFixtures()
        let zNorm = try loadNumpy(url: parityDir.appendingPathComponent("z_norm.npy"))
        let zDenormGolden = try loadNumpy(url: parityDir.appendingPathComponent("z_denorm.npy"))
        let zDenorm = denormalizeLatents22(zNorm)
        eval(zDenorm)
        XCTAssertLessThan(maxAbsDiff(zDenorm, zDenormGolden), 1e-5)
    }

    /// Full decode gate: decode the fixed denormalized latent on the CPU stream and
    /// compare to the video golden — bit-exact (0.0) in practice; tolerances leave a
    /// small margin for future fp jitter while still catching any real regression.
    func testDecodeMatchesGolden() throws {
        try requireFixtures()
        try Device.withDefaultDevice(Device(.cpu)) {
            let decoder = try loadDecoder()
            let zDenorm = try loadNumpy(url: parityDir.appendingPathComponent("z_denorm.npy"))
            let videoGolden = try loadNumpy(url: parityDir.appendingPathComponent("video.npy"))

            let video = decoder(zDenorm)
            eval(video)

            XCTAssertEqual(video.shape, videoGolden.shape, "decoded video shape mismatch")
            let maxd = maxAbsDiff(video, videoGolden)
            let meand = meanAbsDiff(video, videoGolden)
            print("[vae22 parity] decode max-abs=\(maxd) mean-abs=\(meand) shape \(video.shape)")
            XCTAssertLessThan(meand, 1e-5, "vae22 decode mean-abs \(meand)")
            XCTAssertLessThan(maxd, 1e-3, "vae22 decode max-abs \(maxd)")
        }
    }

    /// Stage bisector (diagnostic): replicate the oracle's staged decode and print
    /// the per-stage max/mean vs `st_*.npy`. Stages are ≤6e-5 until the first
    /// big-spatial conv; useful for localizing any future regression.
    func testDecodeStagesMatchGolden() throws {
        try requireFixtures()
        if !FileManager.default.fileExists(atPath: parityDir.appendingPathComponent("st_conv2.npy").path) {
            throw XCTSkip("stage fixtures (st_*.npy) not present")
        }
        try Device.withDefaultDevice(Device(.cpu)) {
            let decoder = try loadDecoder()
            func check(_ name: String, _ x: MLXArray) throws {
                let g = try loadNumpy(url: parityDir.appendingPathComponent("st_\(name).npy"))
                eval(x)
                let d = x.shape == g.shape ? maxAbsDiff(x, g) : Float.nan
                let m = x.shape == g.shape ? meanAbsDiff(x, g) : Float.nan
                print("[stage \(name)] max=\(d) mean=\(m) shape=\(x.shape)")
            }
            let z = try loadNumpy(url: parityDir.appendingPathComponent("z_denorm.npy"))
            let dec = decoder.decoder
            var x = decoder.conv2(z); try check("conv2", x)
            x = dec.conv1(x); try check("conv1", x)
            for (i, layer) in dec.middle.enumerated() {
                switch layer {
                case let r as V22ResidualBlock: x = r(x)
                case let a as V22AttentionBlock: x = a(x)
                default: break
                }
                try check("mid\(i)", x)
            }
            for (i, layer) in dec.upsamples.enumerated() {
                x = (layer as! V22UpResidualBlock)(x, firstChunk: true)
                try check("up\(i)", x)
            }
            x = dec.head(x); try check("head", x)
        }
    }
}
